insert into houses (id, name, status, price, price_without_vat, usable_area, plot_area, rooms, bathrooms, hero_image, floorplan_image, herb_icon, house_card_pdf, description)
values
  ('1',  'Dům 1 – Šalvěj',       'Volný', 11604900, 0, '149.4', '411',  5, 2, '/photos/web_f2.jpg',     '/photos/F1 resize.jpg', '/images/byliny/salvej.png',      '/karty domu/Dum 1.pdf',  'Síla, stabilita a moudrost. Moderní domov s důrazem na dlouhodobý komfort.'),
  ('2',  'Dům 2 – Chrpa',         'Volný', 11705900, 0, '149.4', '410',  5, 2, '/photos/F1 resize.jpg',  '/photos/web_f2.jpg',    '/images/byliny/chrpa.png',       '/karty domu/Dum 2.pdf',  'Výraz přírodní elegance a charakteru. Dům, který vyniká osobitostí a nadčasovým stylem.'),
  ('3',  'Dům 3 – Pampeliška',    'Volný', 10998900, 0, '149.4', '403',  5, 2, null,                     null,                    '/images/byliny/pampeliska.png',  '/karty domu/Dum 3.pdf',  'Přirozenost, lehkost a volnost. Domov, který nabízí prostor pro nové začátky a radost z bydlení.'),
  ('4',  'Dům 4 – Heřmánek',      'Volný', 10998900, 0, '149.4', '402',  5, 2, null,                     null,                    '/images/byliny/hermanek.png',    '/karty domu/Dum 4.pdf',  'Klid, harmonie a přirozená rovnováha. Ideální místo pro odpočinek a každodenní pohodu.'),
  ('5',  'Dům 5 – Mateřídouška',  'Volný', 11301900, 0, '149.4', '401',  5, 2, null,                     null,                    '/images/byliny/materidouška.png','/karty domu/Dum 5.pdf',  'Teplo domova a blízkost přírody. Útulné bydlení s klidnou, rodinnou atmosférou.'),
  ('6',  'Dům 6 – Zvonek',        'Volný', 11604900, 0, '149.4', '401',  5, 2, null,                     null,                    '/images/byliny/zvonek.png',      '/karty domu/Dum 6.pdf',  'Lehkost a vzdušnost propojená s okolní krajinou. Dům plný světla a otevřených výhledů.'),
  ('7',  'Dům 7 – Prvosenka',     'Volný', 11604900, 0, '149.4', '401',  5, 2, null,                     null,                    '/images/byliny/prvosenka.png',   '/karty domu/Dum 7.pdf',  'Nové začátky a svěžest. Světlý domov, který vítá každý nový den.'),
  ('8',  'Dům 8 – Violka',        'Volný', 11705900, 0, '149.4', '401',  5, 2, null,                     null,                    '/images/byliny/violka.png',      '/karty domu/Dum 8.pdf',  'Něžnost a elegance s klidnou atmosférou. Domov pro pohodové a harmonické bydlení.'),
  ('9',  'Dům 9 – Pomněnka',      'Volný', 15139900, 0, '207.7', '401',  7, 2, null,                     null,                    '/images/byliny/pomenka.png',     '/karty domu/dum 9.pdf',  'Jemnost a trvalé hodnoty. Místo, ke kterému se budete vždy rádi vracet.'),
  ('10', 'Dům 10 – Jetel',        'Volný', 15442900, 0, '207.7', '401',  7, 2, null,                     null,                    '/images/byliny/jetel.png',       '/karty domu/dum 10.pdf', 'Symbol štěstí a hojnosti. Promyšlené bydlení s důrazem na praktičnost a pohodu.'),
  ('11', 'Dům 11 – Sedmikráska',  'Volný', 15745900, 0, '197.7', '1304', 5, 2, null,                     null,                    '/images/byliny/sedmikraska.png', '/karty domu/Dum 11.pdf', 'Jemnost a klid v harmonickém prostředí. Ideální místo pro pohodové a vyvážené bydlení.'),
  ('12', 'Dům 12 – Kopretina',    'Volný', 15049000, 0, '197.7', '978',  5, 2, null,                     null,                    '/images/byliny/kopretina.png',   '/karty domu/Dum 12.pdf', 'Symbol jednoduchosti, světla a otevřeného prostoru. Dům s příjemnou atmosférou pro každodenní rodinný život.')
on conflict (id) do nothing;
